[package]
name = "parser_generator"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
lexer = { path = "../lexer" }

[dependencies]
error_handler = { path = "../error_handler" }

[features]
debug-utils = []
