[package]
name = "semantic_analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
ast = { path = "../ast" }
generator = { path = "../generator" }

[dev-dependencies]
parser = { path = "../parser" }
