[package]
name = "runner"
version = "0.1.0"
edition = "2024"

[dependencies]
generator = { path = "../generator" }
semantic_analyzer = { path = "../semantic_analyzer" }
generated_parser = { path = "../generated_parser" }
ast = { path = "../ast" }
error_handler = { path = "../error_handler" }
