[package]
name = "runner"
version = "0.1.0"
edition = "2024"

[dependencies]
generator = { path = "../generator" }
semantic_analyzer = { path = "../semantic_analyzer" }
parser = { path = "../parser" }
ast = { path = "../ast" }

